name: Test & deploy dev

on: [push]

jobs:
  dev:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    - name: Run Tests
      run: |
        make dynamo
        sleep 5
        make ci-server
        sleep 5
        pytest -v
      env:
        # pynamodb needs credentails to be set, even if they're not used in local mode 🤷‍♂️
        AWS_ACCESS_KEY_ID: "fake ID"
        AWS_SECRET_ACCESS_KEY: "fake secret"
    - name: Deploy dev
      run: chalice deploy --stage dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-north-1"

