name: Test & deploy dev

on: [push]

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Run Tests
        run: |
          make dynamo DB_PORT=8000
          sleep 5
          make config
          pipenv shell
          make ci-server
          sleep 5
          pipenv run pytest -v
        env:
          # pynamodb needs credentails to be set, even if they're not used in local mode 🤷‍♂️
          AWS_ACCESS_KEY_ID: "fake ID"
          AWS_SECRET_ACCESS_KEY: "fake secret"
          DB_HOST: "http://localhost:8000"
      - name: Deploy dev
        run: |
          make config CHALICE_API_KEY=$CHALICE_API_KEY
          pipenv run chalice deploy --dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-north-1"
          CHALICE_API_KEY: ${{ secrets.CHALICE_API_KEY_DEV }}
