name: deploy prod
on:
  workflow_run:
    workflows: ["Test & deploy dev"]
    branches: [master]
    types:
      - completed

jobs:
  prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Deploy prod
        run: |
          make config CHALICE_API_KEY=$CHALICE_API_KEY
          pipenv run chalice deploy --stage prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-north-1"
          CHALICE_API_KEY: ${{ secrets.CHALICE_API_KEY_PROD }}
